backend:
  name: git-gateway
  branch: main

media_folder: "public/gallery/uploads"
public_folder: "/gallery/uploads"

locale: "cs"

collections:
  - name: "news"
    label: "Aktuality"
    label_singular: "Článek"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss.SSSZ", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Krátký popis", name: "excerpt", widget: "string" }
      - { label: "Náhledový obrázek", name: "image", widget: "image" }
      - label: "Galerie fotek"
        name: "images"
        widget: "list"
        allow_add: true
        fields:
          - { label: "Fotka", name: "src", widget: "image" }
      - { label: "Obsah", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Fotogalerie"
    label_singular: "Galerie"
    folder: "src/content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss.SSSZ", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Náhledový obrázek", name: "cover", widget: "image" }
      - label: "Fotky"
        name: "photos"
        widget: "list"
        allow_add: true
        fields:
          - { label: "Fotka", name: "src", widget: "image" }
